// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using T3_09.Data;

#nullable disable

namespace T3_09.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202012957_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("T3_09.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreApoderado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEstudiante");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("T3_09.Models.Matricula", b =>
                {
                    b.Property<int>("IdMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatricula"));

                    b.Property<string>("CodigoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int?>("IdPago")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdVacante")
                        .HasColumnType("int");

                    b.HasKey("IdMatricula");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdPago");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdVacante");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("T3_09.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<string>("CodigoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadBancaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.HasKey("IdPago");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("T3_09.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("DesRol")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomRol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdRol");

                    b.ToTable("Rols");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            DesRol = "Administrador",
                            NomRol = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            DesRol = "Padre de Familia",
                            NomRol = "Usuario"
                        });
                });

            modelBuilder.Entity("T3_09.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ApeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("idRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            ApeUsuario = "Sistema",
                            Correo = "admin@sanandres.edu.pe",
                            NomUsuario = "Adminsanandres",
                            Password = "admin720650",
                            idRol = 1
                        });
                });

            modelBuilder.Entity("T3_09.Models.Vacante", b =>
                {
                    b.Property<int>("IdVacante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVacante"));

                    b.Property<int>("CuposDisponibles")
                        .HasColumnType("int");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdVacante");

                    b.ToTable("Vacantes");

                    b.HasData(
                        new
                        {
                            IdVacante = 1,
                            CuposDisponibles = 28,
                            Grado = "1ro Secundaria",
                            Seccion = "A"
                        },
                        new
                        {
                            IdVacante = 2,
                            CuposDisponibles = 15,
                            Grado = "1ro Secundaria",
                            Seccion = "B"
                        },
                        new
                        {
                            IdVacante = 3,
                            CuposDisponibles = 5,
                            Grado = "1ro Secundaria",
                            Seccion = "C"
                        },
                        new
                        {
                            IdVacante = 4,
                            CuposDisponibles = 30,
                            Grado = "2do Secundaria",
                            Seccion = "A"
                        },
                        new
                        {
                            IdVacante = 5,
                            CuposDisponibles = 22,
                            Grado = "2do Secundaria",
                            Seccion = "B"
                        },
                        new
                        {
                            IdVacante = 6,
                            CuposDisponibles = 10,
                            Grado = "2do Secundaria",
                            Seccion = "C"
                        },
                        new
                        {
                            IdVacante = 7,
                            CuposDisponibles = 18,
                            Grado = "3ro Secundaria",
                            Seccion = "A"
                        },
                        new
                        {
                            IdVacante = 8,
                            CuposDisponibles = 0,
                            Grado = "3ro Secundaria",
                            Seccion = "B"
                        },
                        new
                        {
                            IdVacante = 9,
                            CuposDisponibles = 25,
                            Grado = "3ro Secundaria",
                            Seccion = "C"
                        },
                        new
                        {
                            IdVacante = 10,
                            CuposDisponibles = 12,
                            Grado = "4to Secundaria",
                            Seccion = "A"
                        },
                        new
                        {
                            IdVacante = 11,
                            CuposDisponibles = 29,
                            Grado = "4to Secundaria",
                            Seccion = "B"
                        },
                        new
                        {
                            IdVacante = 12,
                            CuposDisponibles = 8,
                            Grado = "4to Secundaria",
                            Seccion = "C"
                        },
                        new
                        {
                            IdVacante = 13,
                            CuposDisponibles = 20,
                            Grado = "5to Secundaria",
                            Seccion = "A"
                        },
                        new
                        {
                            IdVacante = 14,
                            CuposDisponibles = 14,
                            Grado = "5to Secundaria",
                            Seccion = "B"
                        },
                        new
                        {
                            IdVacante = 15,
                            CuposDisponibles = 2,
                            Grado = "5to Secundaria",
                            Seccion = "C"
                        });
                });

            modelBuilder.Entity("T3_09.Models.Matricula", b =>
                {
                    b.HasOne("T3_09.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("T3_09.Models.Pago", "Pago")
                        .WithMany()
                        .HasForeignKey("IdPago");

                    b.HasOne("T3_09.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("T3_09.Models.Vacante", "Vacante")
                        .WithMany()
                        .HasForeignKey("IdVacante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Pago");

                    b.Navigation("Usuario");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("T3_09.Models.Usuario", b =>
                {
                    b.HasOne("T3_09.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("T3_09.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
